// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", // `prisma db seed` 会跑这个
  },
  datasource: {
    // CLI（migrate / introspect）走直连，避开连接池对 DDL 加锁的干扰
    url: process.env["DIRECT_URL"],
  },
});
